### ISSUE TITLE
Is it feasible to use CH347 to drive the SPI interface screen?

### ISSUE THREAD

**Issue by modi12jin** [i2cy/CH347-HIDAPI#2]
Sorry for thinking about it, I want to know if CH347 supports three-wire SPI mode (9-bit data)?

![20201201154728186](https://github.com/i2cy/CH347-HIDAPI/assets/40233017/6d5758b6-7469-4b47-bd0a-945a519db26e)

**Comment by i2cy** [comment]
I think ch347 support only standard 4-wire SPI mode, you can always check whether some kind of feature availiable in their chip datasheet.

**Comment by modi12jin** [comment]
@i2cy It seems that 9bit is not supported
It should be able to use LCD four-wire SPI (CLK, MOSI, CS, DC)?
